# Generated by Django 4.2.10 on 2024-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_programming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonxuser',
            name='finished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
